### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by adrian-ludwig** [pschmitt/docker-plantgateway#1]
Thank you for this! I was going to do the same but found your project.
No problem at all using it with Hass.io ;-) Just had to google around for docker hub image.

Thank you @pschmitt !

**Comment by pschmitt** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/8640342-332715170_1-s4-v1.png?transparent=1&palette=1&width=246)
